name: dqn

buffer_size: 1_000_000
train_every: 64
batch_size: 4096
gamma: 0.95
reward_weights: null
max_grad_norm: 10

gradient_steps: 512

q_net:
  hidden_units: [256, 128]
  lr: 0.0005

epsilon_start: 1.0
epsilon_finish: 0.05
anneal_time: 2000

target_update_interval: 4
tau: 0.005

use_double: false

action_transform: discrete:2
