name: psro

# ppo
train_every: 64
num_minibatches: 16
ppo_epochs: 4
clip_param: 0.1 # 0.2 可能需要搜索
entropy_coef: 0.001 # 0.01
gae_lambda: 0.95
gamma: 0.995 # 0.99
max_grad_norm: 10.0
normalize_advantages: True

critic_input: obs # `obs` or `state`

actor:
  lr: 0.0005
  lr_scheduler:
  lr_scheduler_kwargs:

  # mlp
  hidden_units: [256, 128, 128]
  layer_norm: true

  weight_decay: 0.0
  gain: 0.01

  create_dist_func: default

critic:
  num_critics: 1
  value_norm:
    class: ValueNorm1
    kwargs:
      beta: 0.995

  lr: 0.0005
  lr_scheduler:
  lr_scheduler_kwargs:

  # mlp
  hidden_units: [256, 128, 128]
  layer_norm: true

  weight_decay: 0.0
  gain: 0.01

  use_huber_loss: true
  huber_delta: 10
